# Generated by Django 5.1.4 on 2024-12-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('prefix', models.FilePathField(allow_files=False, allow_folders=True)),
                ('title', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
